[package]
name = "vm-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
vsock = "0.4"

[[bin]]
name = "vm-agent"
path = "src/main.rs"

# Build static binaries by default for deployment in minimal environments
[profile.release]
lto = true
codegen-units = 1
panic = "abort"
