[package]
name = "hyperlight-agents-common"
version = "0.1.0"
edition = "2021"

[dependencies]
hyperlight-common = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
