[build]
# Default target for the workspace
# target = "x86_64-unknown-linux-gnu"  # Commented out to use system default

[alias]
build-all = "build --workspace"
xtask = "run --package xtask --"
build-release = "build --workspace --release"
build-main = "build -p hyperlight-agents-common -p hyperlight-agents-host"
run-host = "run -p hyperlight-agents-host"

# Clean all
clean-all = "clean --workspace"