# Use Alpine as a small base image
FROM alpine:latest

# Install only essential runtime packages
RUN apk update && apk add --no-cache \
    bash \
    ca-certificates \
    openssl \
    curl \
    iproute2 \
    coreutils \
    caddy \
    git \
    util-linux

# The vm-agent binary and init.sh script are added during the Docker build process.
COPY vm-agent /usr/bin/vm-agent
RUN chmod +x /usr/bin/vm-agent

# Prepare folder for root overlay
RUN mkdir /mnt/tmpfs

COPY init.sh /sbin/init
RUN chmod +x /sbin/init

# Create a symlink for compatibility
RUN ln -sf /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2
