[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
  "-C",
  "code-model=small",
  "-C",
  "link-args=-e entrypoint",
]
linker = "rust-lld"

[profile.release]
opt-level = 0
panic = "abort"

[profile.dev]
opt-level = 0
panic = "abort"